name: spdx_lic_detector
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.1.2
  dmp:
    git: https://github.com/bharat-1809/dmp.git

dev_dependencies:
  pedantic: ^1.10.0
